version: '3'
services:
  web:
    build:
      context: ./application
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SINATRA_PORT=${SINATRA_PORT}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${SINATRA_PORT}:${SINATRA_PORT}"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"